### ISSUE TITLE
Could not find @ember-apply/embroider or embroider on npm

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-apply#375]
Not sure where is the issue. But I believe this will be project agnostic?

```
❯ npx ember-apply embroider
ℹ Skypack unavailable, downloading from npm
✖ Could not find @ember-apply/embroider or embroider on npm
AssertionError [ERR_ASSERTION]: Could not find @ember-apply/embroider or embroider on npm
    at downloadFromNpm (file:///Users/michal/.npm/_npx/4a3d1908b81a92e4/node_modules/ember-apply/src/cli/resolve.js:152:3)
    at async resolveApplyable (file:///Users/michal/.npm/_npx/4a3d1908b81a92e4/node_modules/ember-apply/src/cli/resolve.js:34:6)
    at async getApplyable (file:///Users/michal/.npm/_npx/4a3d1908b81a92e4/node_modules/ember-apply/src/cli/index.js:85:25)
    at async run (file:///Users/michal/.npm/_npx/4a3d1908b81a92e4/node_modules/ember-apply/src/cli/index.js:66:21)
    at async Object.handler (file:///Users/michal/.npm/_npx/4a3d1908b81a92e4/node_modules/ember-apply/src/cli/index.js:44:9) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}
```

Tried on [this repository](https://gitlab.com/michal-bryxi/open-source/ember-intl-changeset-validations/-/tree/master).

**Comment by NullVoxPopuli** [comment]
For your test app, you don't want to use this tool.

You'd want to use ember try and have ember-cli-build like here: https://github.com/embroider-build/addon-blueprint/blob/main/files/test-app-overrides/ember-cli-build.js#L12
