### ISSUE TITLE
tailwind-webpack issue

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-apply#495]
Whups :o)

```
npx ember-apply tailwind-webpack
ℹ Skypack unavailable, downloading from npm
ℹ Applying: tailwind-webpack
ℹ If there are any bugs with this applyable, feel free to report at https://github.com/NullVoxPopuli/ember-apply/issues
✖ `import` can only be used in `import()` or `import.meta`. (1:1)
SyntaxError: `import` can only be used in `import()` or `import.meta`. (1:1)
    at constructor (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:356:19)
    at TypeScriptParserMixin.raise (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:3223:19)
    at TypeScriptParserMixin.parseExprAtom (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:11101:16)
    at TypeScriptParserMixin.parseExprSubscripts (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:10857:23)
    at TypeScriptParserMixin.parseUpdate (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:10840:21)
    at TypeScriptParserMixin.parseMaybeUnary (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:10816:23)
    at TypeScriptParserMixin.parseMaybeUnary (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:9696:18)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:10654:61)
    at TypeScriptParserMixin.parseExprOps (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:10659:23)
    at TypeScriptParserMixin.parseMaybeConditional (/private/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/ember-apply-runtime---ULPxcP/node_modules/@babel/parser/lib/index.js:10636:23) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnsupportedImport',
  loc: Position { line: 1, column: 1, index: 1 },
  pos: 1
}
```

No idea what is it complaining about?

**Comment by NullVoxPopuli** [comment]
what project did you run that in? anything open source?

my hunch is that it's a project with no type=module, and something automatically assumed commonjs

**Comment by MichalBryxi** [comment]
It's this one: https://github.com/MichalBryxi/flugmodus/tree/ember-apply-test 

In my last commit I added `"type": "module"` to `package.json` but still the same result.

**Comment by MichalBryxi** [comment]
Hmm I think I can see it: `    beforeFirst: 'skipBabel: [',` was a bit naiive...

**Comment by MichalBryxi** [comment]
Can I run `ember-apply` on my project from local branch? I know just about `npx`, but that will take it from the published version...

**Comment by NullVoxPopuli** [comment]
> on my project from local branch? 

yeah, like this: 

```bash
node ../path/to/ember-apply/src/cli/index.js ../path/to/applayable/index.js
```

**Comment by MichalBryxi** [comment]
A-ha. The project is not the newest. Embroider was not enabled and in `.ember-cli-build.js` there is no:

```
  return require('@embroider/compat').compatBuild(app, Webpack, {
    skipBabel: [ << this is what we are trying to catch on
```

**Comment by NullVoxPopuli** [comment]
should probably throw a custom error or something if embroider isn't active
