### ISSUE TITLE
Volta isn't working

### ISSUE THREAD

**Issue by tcjr** [NullVoxPopuli/ember-apply#524]
I tried running the volta applyable on a brand new ember project and it's failing with this stack trace:

```
~/dev/tcjr/my-app (main) » npx ember-apply volta                                                          
ℹ Downloading from npm...
ℹ Applying: volta
ℹ If there are any bugs with this applyable, feel free to report at https://github.com/NullVoxPopuli/ember-apply/issues
✖ Command failed with exit code 1: which volta
Error: Command failed with exit code 1: which volta
    at makeError (file:///private/var/folders/_d/3_dky5cs1h95dm39yvx6yhh80000gn/T/ember-apply-runtime---I7YzOk/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///private/var/folders/_d/3_dky5cs1h95dm39yvx6yhh80000gn/T/ember-apply-runtime---I7YzOk/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hasVolta (file:///private/var/folders/_d/3_dky5cs1h95dm39yvx6yhh80000gn/T/ember-apply-runtime---I7YzOk/index.js:34:16)
    at async run (file:///private/var/folders/_d/3_dky5cs1h95dm39yvx6yhh80000gn/T/ember-apply-runtime---I7YzOk/index.js:9:3)
    at async run (file:///Users/tcjr/.npm/_npx/4a3d1908b81a92e4/node_modules/ember-apply/src/cli/index.js:77:3)
    at async Object.handler (file:///Users/tcjr/.npm/_npx/4a3d1908b81a92e4/node_modules/ember-apply/src/cli/index.js:43:9) {
  shortMessage: 'Command failed with exit code 1: which volta',
  command: 'which volta',
  escapedCommand: 'which volta',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  cwd: '/Users/tcjr/dev/tcjr/my-app',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Volta is installed and in the path, so it's not clear to me why it's failing.

```
~/dev/tcjr/my-app (main) » which volta
/Users/tcjr/.volta/bin/volta

~/dev/tcjr/my-app (main) » volta --version
1.1.1
```

Any ideas?

**Comment by NullVoxPopuli** [comment]
What shell do you have? I've only been able to test this on bash, so maybe the execa code i have to verify volta is installed only works for bash?

**Comment by tcjr** [comment]
zsh. On Mac.  I just tried it again with bash and it worked fine.  I guess that was it.

**Comment by NullVoxPopuli** [comment]
hm, any ideas how to fix with zsh?

**Comment by tcjr** [comment]
> hm, any ideas how to fix with zsh?

No, I'm afraid not. I can search a bit and try a few things.
